// <auto-generated />
using System;
using JotaNunesForms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JotaNunesForms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JotaNunesFormsDbContext))]
    partial class JotaNunesFormsDbContextModelSnapshot : ModelSnapshot
    {
        internal static void PopulateTargetModel(ModelBuilder modelBuilder) =>
            new JotaNunesFormsDbContextModelSnapshot().BuildModel(modelBuilder);

        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("formularios", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_exibicao");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("perfil");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasFilter("perfil = 'Terceirizado' AND empresa_id IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.ConviteAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConvidadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("convidado_por_usuario_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<DateTime?>("InvalidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidado_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ConvidadoPorUsuarioId");

                    b.HasIndex("EmpresaId", "CriadoEm");

                    b.HasIndex("UsuarioId");

                    b.ToTable("convites_acesso", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Cpf")
                        .IsUnique();

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.FuncionarioObra", b =>
                {
                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid")
                        .HasColumnName("obra_id");

                    b.Property<DateTime>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.HasKey("FuncionarioId", "ObraId");

                    b.HasIndex("ObraId");

                    b.ToTable("funcionario_obras", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.DocumentoEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<DateTime?>("AnalisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analisado_em");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valido_ate");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("documentos_empresa", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.DocumentoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<DateTime?>("AnalisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analisado_em");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valido_ate");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("documentos_funcionario", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailContato")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email_contato");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razao_social");

                    b.Property<string>("TelefoneContato")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("telefone_contato");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.PagamentoFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ComprovanteEnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("comprovante_enviado_em");

                    b.Property<string>("ComprovanteContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("comprovante_content_type");

                    b.Property<string>("ComprovanteNomeArquivo")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("comprovante_nome_arquivo");

                    b.Property<string>("ComprovanteStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("comprovante_storage_key");

                    b.Property<long?>("ComprovanteTamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("comprovante_tamanho_bytes");

                    b.Property<DateOnly>("Competencia")
                        .HasColumnType("date")
                        .HasColumnName("competencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<DateOnly>("PrazoComprovante")
                        .HasColumnType("date")
                        .HasColumnName("prazo_comprovante");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioId", "Competencia")
                        .IsUnique();

                    b.ToTable("pagamentos_funcionario", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.EventoAuditoriaDocumento", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("ChaveNegocio").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("chave_negocio");
                    b.Property<string>("Codigo").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("codigo");
                    b.Property<DateTime>("OcorreuEm").HasColumnType("timestamp with time zone").HasColumnName("ocorreu_em");
                    b.Property<string>("AtorTipo").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)").HasColumnName("ator_tipo");
                    b.Property<Guid?>("AtorUsuarioId").HasColumnType("uuid").HasColumnName("ator_usuario_id");
                    b.Property<string>("AtorNome").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("ator_nome");
                    b.Property<string>("AtorPerfil").HasMaxLength(40).HasColumnType("character varying(40)").HasColumnName("ator_perfil");
                    b.Property<string>("Escopo").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("escopo");
                    b.Property<string>("OrigemTipo").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("origem_tipo");
                    b.Property<Guid>("DocumentoId").HasColumnType("uuid").HasColumnName("documento_id");
                    b.Property<Guid?>("VersaoId").IsRequired().HasColumnType("uuid").HasColumnName("versao_id");
                    b.Property<int?>("VersaoNumero").IsRequired().HasColumnType("integer").HasColumnName("versao_numero");
                    b.Property<Guid?>("VersaoAnteriorId").HasColumnType("uuid").HasColumnName("versao_anterior_id");
                    b.Property<int?>("VersaoAnteriorNumero").HasColumnType("integer").HasColumnName("versao_anterior_numero");
                    b.Property<Guid>("EmpresaId").HasColumnType("uuid").HasColumnName("empresa_id");
                    b.Property<string>("EmpresaRazaoSocial").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("empresa_razao_social");
                    b.Property<Guid?>("FuncionarioId").HasColumnType("uuid").HasColumnName("funcionario_id");
                    b.Property<string>("FuncionarioNome").HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("funcionario_nome");
                    b.Property<Guid?>("ProcessoId").HasColumnType("uuid").HasColumnName("processo_id");
                    b.Property<Guid?>("ItemChecklistId").HasColumnType("uuid").HasColumnName("item_checklist_id");
                    b.Property<string>("TipoDocumentoRotulo").IsRequired().HasMaxLength(160).HasColumnType("character varying(160)").HasColumnName("tipo_documento_rotulo");
                    b.Property<string>("Motivo").HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("motivo");
                    b.Property<string>("Comentario").HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("comentario");
                    b.Property<DateTime?>("ValidoAte").HasColumnType("timestamp with time zone").HasColumnName("valido_ate");
                    b.HasKey("Id");
                    b.HasIndex("ChaveNegocio").IsUnique().HasDatabaseName("ux_auditoria_eventos_documentais_chave_negocio");
                    b.HasIndex("OcorreuEm", "Id").IsDescending(true, true).HasDatabaseName("ix_auditoria_eventos_documentais_ocorreu_em_id");
                    b.HasIndex("EmpresaId", "OcorreuEm", "Id").IsDescending(false, true, true).HasDatabaseName("ix_auditoria_eventos_documentais_empresa_data_id");
                    b.HasIndex("Codigo", "OcorreuEm", "Id").IsDescending(false, true, true).HasDatabaseName("ix_auditoria_eventos_documentais_codigo_data_id");
                    b.HasIndex("Escopo", "OcorreuEm", "Id").IsDescending(false, true, true).HasDatabaseName("ix_auditoria_eventos_documentais_escopo_data_id");
                    b.HasIndex("OrigemTipo", "DocumentoId", "OcorreuEm").IsDescending(false, false, true).HasDatabaseName("ix_auditoria_eventos_documentais_origem_documento_data");
                    b.ToTable("auditoria_eventos_documentais", table =>
                    {
                        table.HasCheckConstraint("ck_auditoria_eventos_documentais_version_positive", "versao_numero > 0");
                        table.HasCheckConstraint("ck_auditoria_eventos_documentais_previous_version_pair", "(versao_anterior_id IS NULL) = (versao_anterior_numero IS NULL)");
                        table.HasCheckConstraint("ck_auditoria_eventos_documentais_reason_action", "(codigo = 'DocumentoRejeitado' AND motivo IS NOT NULL) OR (codigo <> 'DocumentoRejeitado' AND motivo IS NULL)");
                        table.HasCheckConstraint("ck_auditoria_eventos_documentais_employee_snapshot", "(escopo = 'Funcionario' AND funcionario_id IS NOT NULL AND funcionario_nome IS NOT NULL) OR (escopo <> 'Funcionario' AND funcionario_id IS NULL AND funcionario_nome IS NULL)");
                        table.HasCheckConstraint("ck_auditoria_eventos_documentais_actor_snapshot", "(ator_tipo = 'Usuario' AND ator_usuario_id IS NOT NULL AND ator_perfil IS NOT NULL) OR (ator_tipo = 'Sistema' AND ator_usuario_id IS NULL AND ator_perfil IS NULL AND ator_nome = 'Sistema')");
                    });
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.DocumentoArquivoVersao", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid?>("DocumentoEmpresaId").HasColumnType("uuid").HasColumnName("documento_empresa_id");
                    b.Property<Guid?>("DocumentoFuncionarioId").HasColumnType("uuid").HasColumnName("documento_funcionario_id");
                    b.Property<int>("Numero").HasColumnType("integer").HasColumnName("numero");
                    b.Property<string>("NomeArquivo").IsRequired().HasMaxLength(260).HasColumnType("character varying(260)").HasColumnName("nome_arquivo");
                    b.Property<string>("StorageKey").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("storage_key");
                    b.Property<string>("ContentType").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("content_type");
                    b.Property<long>("TamanhoBytes").HasColumnType("bigint").HasColumnName("tamanho_bytes");
                    b.Property<Guid?>("EnviadoPorUsuarioId").HasColumnType("uuid").HasColumnName("enviado_por_usuario_id");
                    b.Property<DateTime>("EnviadoEm").HasColumnType("timestamp with time zone").HasColumnName("enviado_em");
                    b.Property<bool>("Vigente").HasColumnType("boolean").HasColumnName("vigente");
                    b.HasKey("Id");
                    b.HasIndex("DocumentoEmpresaId", "Numero").IsUnique().HasDatabaseName("ux_documentos_arquivos_versoes_empresa_numero").HasFilter("documento_empresa_id IS NOT NULL");
                    b.HasIndex("DocumentoFuncionarioId", "Numero").IsUnique().HasDatabaseName("ux_documentos_arquivos_versoes_funcionario_numero").HasFilter("documento_funcionario_id IS NOT NULL");
                    b.HasIndex("DocumentoEmpresaId").IsUnique().HasDatabaseName("ux_documentos_arquivos_versoes_empresa_vigente").HasFilter("vigente = TRUE AND documento_empresa_id IS NOT NULL");
                    b.HasIndex("DocumentoFuncionarioId").IsUnique().HasDatabaseName("ux_documentos_arquivos_versoes_funcionario_vigente").HasFilter("vigente = TRUE AND documento_funcionario_id IS NOT NULL");
                    b.HasIndex("EnviadoPorUsuarioId");
                    b.ToTable("documentos_arquivos_versoes", table =>
                    {
                        table.HasCheckConstraint("ck_documentos_arquivos_versoes_origin_xor", "num_nonnulls(documento_empresa_id, documento_funcionario_id) = 1");
                        table.HasCheckConstraint("ck_documentos_arquivos_versoes_numero_positive", "numero > 0");
                        table.HasCheckConstraint("ck_documentos_arquivos_versoes_size_positive", "tamanho_bytes > 0");
                    });
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.DocumentoVersao", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("ItemChecklistId").HasColumnType("uuid").HasColumnName("item_checklist_id");
                    b.Property<int>("Numero").HasColumnType("integer").HasColumnName("numero");
                    b.Property<string>("NomeArquivo").HasMaxLength(260).HasColumnType("character varying(260)").HasColumnName("nome_arquivo");
                    b.Property<string>("StorageKey").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("storage_key");
                    b.Property<string>("ContentType").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("content_type");
                    b.Property<long?>("TamanhoBytes").HasColumnType("bigint").HasColumnName("tamanho_bytes");
                    b.Property<string>("HashSha256").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("hash_sha256");
                    b.Property<string>("CamposJson").HasColumnType("text").HasColumnName("campos_json");
                    b.Property<Guid>("EnviadoPorUsuarioId").HasColumnType("uuid").HasColumnName("enviado_por_usuario_id");
                    b.Property<DateTime>("EnviadoEm").HasColumnType("timestamp with time zone").HasColumnName("enviado_em");
                    b.Property<bool>("Vigente").HasColumnType("boolean").HasColumnName("vigente");
                    b.HasKey("Id");
                    b.HasIndex("ItemChecklistId");
                    b.HasIndex("ItemChecklistId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_documentos_versoes_item_numero");
                    b.HasIndex("ItemChecklistId")
                        .IsUnique()
                        .HasDatabaseName("ux_documentos_versoes_item_vigente")
                        .HasFilter("vigente = TRUE");
                    b.HasIndex("HashSha256");
                    b.ToTable("documentos_versoes", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.DocumentoArquivoVersao", b =>
                {
                    b.HasOne("JotaNunesForms.Domain.Entities.DocumentoEmpresa", null)
                        .WithMany()
                        .HasForeignKey("DocumentoEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("JotaNunesForms.Domain.Entities.DocumentoFuncionario", null)
                        .WithMany()
                        .HasForeignKey("DocumentoFuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                    b.HasOne("JotaNunesForms.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.IntegracaoObra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");
                    b.Property<bool>("AceiteTrabalhador")
                        .HasColumnType("boolean")
                        .HasColumnName("aceite_trabalhador");
                    b.Property<string>("Avaliacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("avaliacao");
                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("conteudo");
                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");
                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");
                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");
                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");
                    b.Property<string>("Instrutor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instrutor");
                    b.Property<Guid>("ItemChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_checklist_id");
                    b.Property<Guid>("MobilizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobilizacao_id");
                    b.Property<string>("MotivoRefazer")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_refazer");
                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid")
                        .HasColumnName("obra_id");
                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .IsFixedLength()
                        .HasColumnName("payload_hash");
                    b.Property<bool>("Refazer")
                        .HasColumnType("boolean")
                        .HasColumnName("refazer");
                    b.Property<DateTime?>("RefazerEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refazer_em");
                    b.Property<Guid?>("RefazerPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("refazer_por_usuario_id");
                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valido_ate");
                    b.HasKey("Id");
                    b.HasIndex("ItemChecklistId");
                    b.HasIndex("ObraId");
                    b.HasIndex("MobilizacaoId", "DataHora", "Id");
                    b.HasIndex("MobilizacaoId", "IdempotencyKey")
                        .IsUnique();
                    b.ToTable("integracoes_obra", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.MovimentoEpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");
                    b.Property<bool>("AceiteTrabalhador")
                        .HasColumnType("boolean")
                        .HasColumnName("aceite_trabalhador");
                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");
                    b.Property<string>("Epi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("epi");
                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");
                    b.Property<Guid>("ItemChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_checklist_id");
                    b.Property<Guid>("MobilizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("mobilizacao_id");
                    b.Property<Guid?>("MovimentoOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("movimento_origem_id");
                    b.Property<string>("NumeroCa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_ca");
                    b.Property<bool>("OrientacaoUso")
                        .HasColumnType("boolean")
                        .HasColumnName("orientacao_uso");
                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .IsFixedLength()
                        .HasColumnName("payload_hash");
                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");
                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_usuario_id");
                    b.Property<bool>("ResponsabilidadeGuarda")
                        .HasColumnType("boolean")
                        .HasColumnName("responsabilidade_guarda");
                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tipo");
                    b.HasKey("Id");
                    b.HasIndex("ItemChecklistId");
                    b.HasIndex("MovimentoOrigemId");
                    b.HasIndex("MobilizacaoId", "CriadoEm", "Id");
                    b.HasIndex("MobilizacaoId", "IdempotencyKey")
                        .IsUnique();
                    b.ToTable("movimentos_epi", (string)null);
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.IntegracaoObra", b =>
                {
                    b.HasOne("JotaNunesForms.Domain.Entities.ItemChecklist", null)
                        .WithMany()
                        .HasForeignKey("ItemChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("JotaNunesForms.Domain.Entities.Mobilizacao", null)
                        .WithMany()
                        .HasForeignKey("MobilizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("JotaNunesForms.Domain.Entities.Obra", null)
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JotaNunesForms.Domain.Entities.MovimentoEpi", b =>
                {
                    b.HasOne("JotaNunesForms.Domain.Entities.ItemChecklist", null)
                        .WithMany()
                        .HasForeignKey("ItemChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("JotaNunesForms.Domain.Entities.Mobilizacao", null)
                        .WithMany()
                        .HasForeignKey("MobilizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("JotaNunesForms.Domain.Entities.MovimentoEpi", null)
                        .WithMany()
                        .HasForeignKey("MovimentoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
